GestorDePaciente/Controllers/ResultLabTestController.cs
using GestorDePaciente.Core.Application.Interfaces.Services.Lab;
using GestorDePaciente.Core.Application.Interfaces.Services.Office.Patient;
using GestorDePaciente.Core.Application.ViewModels;
using GestorDePaciente.Core.Application.ViewModels.Office.Patient;
using GestorDePaciente.Middlewares;
using Microsoft.AspNetCore.Mvc;

namespace GestorDePaciente.Controllers;

public class ResultLabTestController : Controller
{
    private readonly ValidateUserSession _validate;
    private readonly IPatientService _patientService;
    private readonly ILabTestService _labTestService;
    
    public ResultLabTestController(ValidateUserSession validate, IResultTestService resultTestService, IPatientService patientService, ILabTestService labTestService)
    {
        _validate = validate;
        _patientService = patientService;
        _labTestService = labTestService;
    }
    
    public async Task<ActionResult> ResultLabTest(FiltroViewModel filtro, string cedula)
    {
        if (!_validate.HasUser())
        {
            return RedirectToRoute(new { Controller = "Login", Action = "Index" });
        }
        
        ViewBag.Patients = await _patientService.GetAllViewModel();
        ViewBag.LabTest = await _labTestService.GetAllViewModel();
        
        var patients = await _patientService.GetAllViewModel();

        if (cedula != null)
        {
            patients = await _patientService.GetByDni(cedula);
        }
        return View(patients);
    }
}

GestorDePaciente/Views/Shared/_Layout.cshtml
@using GestorDePaciente.Core.Application.ViewModels.Users
@using Microsoft.AspNetCore.Http;
@using GestorDePaciente.Core.Application.Helpers;

@inject IHttpContextAccessor HttpContextAccessor
@{
    UserViewModel user = HttpContextAccessor.HttpContext.Session.Get<UserViewModel>("user");
    var isAdmin = user != null && user.RoleId == 1;
    var isAsistent = user != null && user.RoleId == 2;
}

<!DOCTYPE html>
<html lang="es">
<head>
    <meta charset="utf-8"/>
    <meta name="viewport" content="width=device-width, initial-scale=1.0"/>
    <title>GestorDePaciente | @ViewData["Title"]</title>
    <link href="/img/logo-login.png" rel="icon"/>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css"/>
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.11.3/font/bootstrap-icons.min.css">
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true"/>
    <link rel="stylesheet" href="~/GestorDePaciente.styles.css" asp-append-version="true"/>
    <style>
        .cerrar-sesion{
            background-color: #004063;
            border-radius: 5px;
            transition: ease 0.5s;
        }
        
        .cerrar-sesion:hover{
            background-color: #013956;
        }
        
        .inicio{
            background-color: #005D3E;
            border-radius: 5px;
            transition: ease 0.5s;
        }
        
        .inicio:hover{
            background-color: #003926;
        }
        
        .navb {
            color: black !important;
            transition: ease 0.5s;
        }
        
        .navb:hover {
            color: white !important;
            background-color: #015886;
            border-radius: 5px;
        }
        
    </style>
</head>
<body class="bg-radial-gradient">
<header>
    @if (user != null)
    {
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid d-flex align-items-center position-relative">
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav">
                        <li class="nav-item inicio ps-2 pe-2">
                            <a class="nav-link text-white" asp-area="" asp-controller="Home" asp-action="Home">Inicio</a>
                        </li>
                    </ul>
                    <ul class="navbar-nav position-absolute start-50 translate-middle-x">
                        @if (isAdmin)
                        {
                            <li class="nav-item">
                                <a class="nav-link me-2 navb" asp-area="" asp-controller="User" asp-action="User">Mant. de Usuarios</a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link me-2 navb" asp-area="" asp-controller="Doctor" asp-action="Doctor">Mant. de Medicos</a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link navb" asp-area="" asp-controller="LabTest" asp-action="LabTest">Mant. de Pruebas de Laboratorio</a>
                            </li>
                        }
                        @if (isAsistent)
                        {
                            <li class="nav-item">
                                <a class="nav-link me-2 navb" asp-area="" asp-controller="Patient" asp-action="Patient">Mant. de Pacientes</a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link me-2 navb" asp-area="" asp-controller="ResultLabTest" asp-action="ResultLabTest">Mant. de Resultados del Laboratorio</a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link navb" asp-area="" asp-controller="Appointment" asp-action="Appointment">Mant. de Citas de Pacientes</a>
                            </li>
                        }
                    </ul>
                    <ul class="navbar-nav ms-auto">
                        <li class="nav-item cerrar-sesion ps-2 pe-2">
                            <a class="nav-link text-white" asp-area="" asp-controller="Login" asp-action="Logout"><i class="bi bi-box-arrow-right"></i> Cerrar Sesión</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    }
</header>
<div class="container">
    <main role="main" class="pb-3">
        @RenderBody()
    </main>
</div>

<footer class="footer text-muted">
    <div class="container text-center">
        &copy; 2024 - GestorDePaciente - Arisneudy Santana
    </div>
</footer>
<script src="~/lib/jquery/dist/jquery.min.js"></script>
<script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
<script src="~/js/site.js" asp-append-version="true"></script>
@await RenderSectionAsync("Scripts", required: false)
</body>
</html>